import type { Metadata } from "next";
import { Roboto_Serif } from "next/font/google";
import "./globals.css";

const roboto_serif = Roboto_Serif({
 variable: "--font-geist-sans",
 subsets: ["latin"],
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <body
    suppressHydrationWarning
    className={`${roboto_serif.variable} antialiased`}
   >
    {children}
   </body>
  </html>
 );
}
